Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "16384"
    vb.cpus = "8"
    vb.customize ["modifyvm", :id, "--vram", "256" ]
    vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "play.yaml"
  end
end
