---
- hosts: all
  become: True
  gather_facts: False
  pre_tasks:
    - name: add ceph repo to hosts
      template:
        src: ceph.repo.j2
        dest: /etc/yum.repos.d/ceph.repo
        mode: 0644
        owner: root
        group: root

  tasks:
    - name: Disable SELinux
      selinux:
        policy: targeted
        state: permissive

    - name: Install podman, python3
      package:
        name:
          - podman
          - python3
          - cephadm
        state: present

- hosts: mon
  become: True
  gather_facts: False
  tasks:
    - name: Create .ssh directory for user root
      file:
        path: /root/.ssh
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Generate ssh keys for root user
      openssh_keypair:
        path: /root/.ssh/id_rsa

    - name: Fetch public ssh keys from mgrs
      fetch:
        src: /root/.ssh/id_rsa.pub
        dest: buffer/id_rsa.pub
        flat: True

- hosts: osd
  become: True
  gather_facts: True
  tasks:
    - name: Roll out ssh keys to root user
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'buffer/id_rsa.pub') }}"
