VAGRANTFILE_API_VERSION = "2"

# mgrs = {
#   "ceph-mgr-001" => { :ip => "192.168.33.10", :cpus => 2, :mem => 2048 }
# }

mons = {
  "ceph-mon-001" => { :ip => "192.168.33.11", :cpus => 4, :mem => 4096 }
}

osds = {
  "ceph-osd-001" => { :ip => "192.168.33.21", :cpus => 4, :mem => 2048 },
  "ceph-osd-002" => { :ip => "192.168.33.22", :cpus => 4, :mem => 2048 },
  "ceph-osd-003" => { :ip => "192.168.33.23", :cpus => 4, :mem => 2048 },
  "ceph-osd-004" => { :ip => "192.168.33.24", :cpus => 4, :mem => 2048 },
  "ceph-osd-005" => { :ip => "192.168.33.25", :cpus => 4, :mem => 2048 }
}

clients = {
  "ceph-client-001" => { :ip => "192.168.33.31", :cpus => 2, :mem => 2048 }
}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # mgrs.each_with_index do |(hostname, info), index|
  #   config.vm.define hostname do |cfg|
  #     cfg.vm.provider :virtualbox do |vb, override|
  #       config.vm.box = "rockylinux/8"
  #       override.vm.network :private_network, ip: "#{info[:ip]}"
  #       override.vm.hostname = hostname
  #       vb.name = hostname
  #       vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
  #     end
  #   end
  # end

  mons.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "rockylinux/8"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end
    end
  end

  osds.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "rockylinux/8"
        (1..3).each do |i|
          override.vm.disk :disk, name: "osd#{i}", size: "10GB"
        end
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end
    end
  end

  clients.each_with_index do |(hostname, info), index|
    config.vm.define hostname do |cfg|
      cfg.vm.provider :virtualbox do |vb, override|
        config.vm.box = "rockylinux/8"
        override.vm.network :private_network, ip: "#{info[:ip]}"
        override.vm.hostname = hostname
        vb.name = hostname
        vb.customize ["modifyvm", :id, "--memory", info[:mem], "--cpus", info[:cpus], "--hwvirtex", "on"]
      end
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "play.yaml"
    ansible.groups = {
      #{}"mgr" => ["ceph-mgr-001"],
      "mon" => ["ceph-mon-001"],
      "osd" => ["ceph-osd-00[1:5]"]
    }
  end
end
